version: "3"
services:
  fluentd:
    depends_on:
      - elasticsearch
    networks:
      - default
    build: ./fluentd
    environment:
      - FLUENT_UID=0
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./fluentd/logs:/tmp/logs
      - ./output-logs:/tmp/output-logs
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "9880:9880"

  elasticsearch:    
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    environment:
      - "discovery.type=single-node"
    networks:
      - default

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    networks:
      - default
    ports:
      - "5601:5601"
    